
	<!-- ================== BEGIN BASE CSS STYLE ================== -->
	<link href="../../Content/plugins/jquery-ui/themes/base/minified/jquery-ui.min.css" rel="stylesheet" />
    <link href="../../Content/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="../../Content/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" /> 
    <link href="../../Content/plugins/ionicons/css/ionicons.min.css" rel="stylesheet" />
    <link href="../../Content/css/animate.min.css" rel="stylesheet" />
    <link href="../../Content/plugins/bootstrap-calendar/css/bootstrap_calendar.css" rel="stylesheet" />
    <link href="../../Content/css/main.min.css" rel="stylesheet" />
	
	<!--[if lt IE 9]>
	    <script src="Content/crossbrowserjs/excanvas.min.js"></script>
	<![endif]-->

    <!-- ================== BEGIN BASE JS ================== -->
    <!--<script src="Content/plugins/jquery/jquery-1.9.1.min.js"></script>-->
    <script src="../../Content/plugins/jquery/jquery-2.1.4.min.js"></script>
    <script src="../../Content/plugins/jquery/jquery-migrate-1.1.0.min.js"></script>
    <script src="../../Content/plugins/jquery-ui/ui/minified/jquery-ui.min.js"></script>
    <script src="../../Content/plugins/bootstrap/js/bootstrap.min.js"></script>
  
    <!--[if lt IE 9]>
        <script src="../../Content/crossbrowserjs/html5shiv.js"></script>
        <script src="../../Content/crossbrowserjs/respond.min.js"></script>
    <![endif]-->